---
title: "EY71"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)

df <- read_excel("~/Documents/Experiments/11.3.25 EY71 Read 2.xlsx", 
    sheet = "Lum")
g <- read_excel("~/Documents/Experiments/11.3.25 EY71 Read 2.xlsx", 
    sheet = "OD")
h <- read_excel("~/Documents/Experiments/11.3.25 EY71 Read 2.xlsx", 
    sheet = "OD2")
```

```{r Lum}

newdf <- df %>% filter_all(any_vars(!is.na(.)))

A12 <-aggregate(A12 ~ ID, data = newdf, max)
C12 <-aggregate(C12 ~ ID, data = newdf, max)
E12 <-aggregate(E12 ~ ID, data = newdf, max)
G12 <-aggregate(G12 ~ ID, data = newdf, max)
A1 <-aggregate(A1 ~ ID, data = newdf, max)
A3 <-aggregate(A3 ~ ID, data = newdf, max)
A5 <-aggregate(A5 ~ ID, data = newdf, max)
C1 <-aggregate(C1 ~ ID, data = newdf, max)
C3 <-aggregate(C3 ~ ID, data = newdf, max)
C5 <-aggregate(C5 ~ ID, data = newdf, max)
E1 <-aggregate(E1 ~ ID, data = newdf, max)
E3 <-aggregate(E3 ~ ID, data = newdf, max)
E5 <-aggregate(E5 ~ ID, data = newdf, max)


Maxes <- cbind(A12$A12,C12$C12,E12$E12,G12$G12,A1$A1,A3$A3,A5$A5,C1$C1,C3$C3,C5$C5,E1$E1,E3$E3,E5$E5)
colnames(Maxes) <- c('A12','C12','E12','G12','A1','A3','A5','C1','C3','C5','E1','E3','E5')

Hours<- c(0,1,2,3,4,5,6,7,8,9,10,11,11.13,12.13,12.26,13.26,14.26,15.26,16.26,17.26) 

h <- cbind(Maxes, Hours)
h<-as.data.frame(h)

h <- h %>% 
  mutate_at(c('A12','C12','E12','G12','A1','A3','A5','C1','C3','C5','E1','E3','E5','Hours'), as.numeric)

```

```{r}
#colors <- c("steelblue" = "steelblue","black" = "black")

p <- ggplot(h, aes(x=Hours)) + 
  geom_line(aes(y = A1), color="red",size = 1) + 
  geom_line(aes(y = A3), color="red",size = 1) + 
  geom_line(aes(y = A5), color="steelblue",size = 1) + 
  geom_line(aes(y = G12), color="black",size = 1) + 
  geom_line(aes(y = A12), color="black",size = 1) + 
  geom_line(aes(y = C12), color="black",size = 1)+
  geom_line(aes(y = E12), color="black",size = 1)+
labs(title="OD10 104 iLUX Kan P. rettgeri",
        x ="Time (hours)", y = "Luminescence (AU)", color = "Legend")+
 theme_grey(base_size = 20)
p
#ggsave("EY71OD10.png")

p2 <- ggplot(h, aes(x=Hours)) + 
  geom_line(aes(y = C1), color="steelblue",size = 1) +
  geom_line(aes(y = C3), color="red",size = 1) +
  geom_line(aes(y = C5), color="steelblue",size = 1) +
  geom_line(aes(y = G12), color="black",size = 1) + 
  geom_line(aes(y = A12), color="black",size = 1) + 
  geom_line(aes(y = C12), color="black",size = 1)+
  geom_line(aes(y = E12), color="black",size = 1)+
  labs(title="OD1 104 iLUX Kan P. rettgeri",
        x ="Time (hours)", y = "Luminescence (AU)", color = "Legend")+
 theme_grey(base_size = 20)
p2
#ggsave("EY71OD1.png")

p3 <- ggplot(h, aes(x=Hours)) + 
  geom_line(aes(y = E1), color="red",size = 1) + 
  geom_line(aes(y = E3), color="steelblue",size = 1) + 
  geom_line(aes(y = E5), color="steelblue",size = 1) +
  geom_line(aes(y = G12), color="black",size = 1) + 
  geom_line(aes(y = A12), color="black",size = 1) + 
  geom_line(aes(y = C12), color="black",size = 1)+
  geom_line(aes(y = E12), color="black",size = 1)+
  labs(title="OD0.1 104 iLUX Kan P. rettgeri",
        x ="Time (hours)", y = "Luminescence (AU)", color = "Legend")+
 theme_grey(base_size = 20)

p3
#ggsave("EY71OD01.png")
```


```{r}
sp <- ggplot(g, aes(x = CFU, y = Lum, colour = OD))+ 
  scale_y_log10()+scale_x_log10()+
  geom_point(size=2.5) +  xlab("CFU/Fly") + ylab("Luminescence (AU)")
sp + theme(
axis.title.x = element_text(size=14, face="bold"),
axis.title.y = element_text(size=18, face="bold"),
axis.text.x = element_text(face="bold", size=18),
axis.text.y = element_text(face="bold",size=18),
legend.text=element_text(size=18, face='bold'))

#ggsave("whole.png")
```

```{r}
sp <- ggplot(h, aes(x = CFU, y = Lum, colour = Time))+ 
  scale_y_log10()+scale_x_log10()+
  geom_point(size=2.5) +  xlab("CFU/Fly") + ylab("Luminescence (AU)")
sp + theme_grey(base_size = 20)

#ggsave("half.png")
```